Algoritmo "semnome"


Var

   x, y, z, a, b, c, d : real

Inicio

      x <- 2.0
      y <- 3.0
      z <- -7.0
      
      a <- Exp(x, y)   //Variavel a recebe o resultado de x elevado a y
      b <- Raizq(y)    //Variavel b recebe a raiz quadrada de y
      c <- Pi          //Variavel c recebe o valor de pi
      d <- Abs(z)      //Variavel d recebe o valor absoluto de z
      
      escreval(a)
      escreval(b)
      escreval(c)
      escreval(d)

Fimalgoritmo